---

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  become: yes
  become_user: root

- name: Restart newspipe-gunicorn
  ansible.builtin.service:
    name: newspipe-gunicorn
    state: restarted
  become: yes
  become_user: root
